[tool.poetry]
name = "pipelinec"
version = "0.1.0"
description = ""
authors = ["Julian Kemmerer"]
license = "GPT-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.test.dependencies]
hypothesis = "^6.54.4"
pytest-golden = "^0.2.2"
pytest = "^7.1.2"
coverage = "^6.4.4"


[tool.poetry.group.analysis.dependencies]
vulture = "^2.5"


[tool.poetry.group.types.dependencies]
mypy = "^0.971"


[tool.poetry.group.lint.dependencies]
wemake-python-styleguide = "^0.16.1"


[tool.poetry.group.format.dependencies]
yapf = "^0.32.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
