[lint]

ignore = [
    "F841",
    "E721",
    "E401",
    "E722",
    "F821",
    "F401",
    "E402",
    "E741",
    "E731",
    "E713",
    "E401",
    "E711",
    "E712",
    "F811",
    "F541"
]
