// Serializable protocol for fosix syscalls

#pragma once

// This begs to be autogenerated...

#include "fosix.h"
#include "../aws-fpga-dma/dma_msg.h"

// Syscall table
#define syscall_t uint8_t
#define POSIX_READ  0
#define POSIX_WRITE 1
#define POSIX_OPEN  2
#define POSIX_CLOSE 3
#define POSIX_UNKNOWN 255
// Byte[0] = Sycall ID
syscall_t decode_syscall_id(dma_msg_t msg)
{
  syscall_t rv;
  rv = POSIX_UNKNOWN;
  printf("msg.data[0] = %d\n",msg.data[0]);
  if(msg.data[0]==POSIX_READ)
  {
    rv = POSIX_READ;
  }
  else if(msg.data[0]==POSIX_WRITE)
  {
    rv = POSIX_WRITE;
  }
  else if(msg.data[0]==POSIX_OPEN)
  {
    rv = POSIX_OPEN;
  }
  else if(msg.data[0]==POSIX_CLOSE)
  {
    rv = POSIX_CLOSE;
  }
  return rv;
}

// Bytes[1+] are specific to syscall

// OPEN REQ
dma_msg_s open_req_to_dma(open_req_t req)
{
  dma_msg_s msg_stream = DMA_MSG_S_NULL();
  msg_stream.valid = req.valid;  
  
  // Bytes[1-PATH_SIZE] are path
  size_t i;
  for(i=1; i<(PATH_SIZE+1); i=i+1)
  {
    msg_stream.data.data[i] = req.path[i-1];
  }
  
  return msg_stream;
}
open_req_t dma_to_open_req(dma_msg_t msg)
{
  open_req_t req;
  req.valid = decode_syscall_id(msg) == POSIX_OPEN;
  
  // Bytes[1-PATH_SIZE] are path
  size_t i;
  for(i=1; i<(PATH_SIZE+1); i=i+1)
  {
    req.path[i-1] = msg.data[i];
  }
  
  return req;
}

// OPEN RESP
open_resp_t dma_to_open_resp(dma_msg_s msg_stream)
{
  open_resp_t resp;
  resp.valid = (decode_syscall_id(msg_stream.data) == POSIX_OPEN) & msg_stream.valid;
  
  // Byte[1] = fildes
  resp.fildes = msg_stream.data.data[1];
  
  return resp;
}
dma_msg_s open_resp_to_dma(open_resp_t resp)
{
  dma_msg_s msg_stream = DMA_MSG_S_NULL();
  msg_stream.valid = resp.valid;
  
  // Byte[1] = fildes
  msg_stream.data.data[1] = resp.fildes;
  
  return msg_stream;  
}


// WRITE REQ
dma_msg_s write_req_to_dma(write_req_t req)
{
  dma_msg_s msg_stream = DMA_MSG_S_NULL();
  msg_stream.valid = req.valid;  
  
  // Byte[1] = fildes
  msg_stream.data.data[1] = req.fildes;
  // Byte[2] = nbyte
  msg_stream.data.data[2] = req.nbyte;
  // Byte[3-(BUF_SIZE+2)] = buf
  size_t i;
  for(i=3; i<(BUF_SIZE+3); i=i+1)
  {
    msg_stream.data.data[i] = req.buf[i-3];
  }
  
  return msg_stream;
}
write_req_t dma_to_write_req(dma_msg_t msg)
{
  write_req_t req;
  req.valid = decode_syscall_id(msg) == POSIX_WRITE;
  
  // Byte[1] = fildes
  req.fildes = msg.data[1];
  // Byte[2] = nbyte
  req.nbyte = msg.data[2];
  // Byte[3-(BUF_SIZE+2)] = buf
  size_t i;
  for(i=3; i<(BUF_SIZE+3); i=i+1)
  {
    req.buf[i-3] = msg.data[i];
  }
  
  return req;
}


// WRITE RESP
write_resp_t dma_to_write_resp(dma_msg_s msg_stream)
{
  write_resp_t resp;
  resp.valid = (decode_syscall_id(msg_stream.data) == POSIX_WRITE) & msg_stream.valid;
  
  // Byte[1] = nbyte
  resp.nbyte = msg_stream.data.data[1];
  
  return resp;
}
dma_msg_s write_resp_to_dma(write_resp_t resp)
{
  dma_msg_s msg_stream = DMA_MSG_S_NULL();
  msg_stream.valid = resp.valid;
  
  // Byte[1] = nbyte
  msg_stream.data.data[1] = resp.nbyte;
  
  return msg_stream;
}

// C2H
posix_c2h_t dma_to_request(dma_msg_t msg)
{
  posix_c2h_t req = POSIX_C2H_T_NULL();
  req.sys_open.req  = dma_to_open_req(msg);
  req.sys_write.req = dma_to_write_req(msg);
  return req;  
}

// H2C
dma_msg_s response_to_dma(posix_h2c_t resp)
{
  dma_msg_s msg_stream = DMA_MSG_S_NULL();
  msg_stream.valid = 0;
  if(resp.sys_open.resp.valid)
  {
    msg_stream = open_resp_to_dma(resp.sys_open.resp);
  }
  else if(resp.sys_write.resp.valid)
  {
    msg_stream = write_resp_to_dma(resp.sys_write.resp);
  }
  return msg_stream;
}
