# pyright: reportInvalidTypeForm=none
from pypeline import (
    struct,
    NamedTuple,
    uint1_t,
    hw_func,
    Reg,
    make_uint_t,
    _auto_pipeline_with_io_regs,
    hw_arg_types,
    hw_return_type,
    is_hw_func,
)

from fifo import make_fifo
from stream.stream import make_stream_interface, make_stream_t


def make_stream_auto_pipeline(func, *, latency=None, start_latency=None, max_latency=None):
    """Wraps a combinational hardware function in an AUTO_PIPELINE'd instance (with
    registered input/output) plus a free-running output FIFO, exposing a single
    valid/ready stream interface around it — pypeline equivalent of PipelineC's
    GLOBAL_VALID_READY_PIPELINE_INST macro, minus the global wires: this is one
    locally-instantiated function instead of two MAIN funcs joined by globals.

    The FIFO and in-flight counter are sized automatically from the
    AUTO_PIPELINE'd instance's .latency — the tool-discovered pipeline depth —
    so there is no MAX_IN_FLIGHT parameter to guess. .latency reads 0 until
    the pipelinec driver's pin-and-confirm pass installs the real value
    (native sim / --comb builds stay at 0 unless latency=N fixes it). With
    core latency L, up to L+5 words are in flight, enough to accept one word
    per cycle while the consumer is ready; a word accepted on cycle t is
    presented on cycle t+L+4. Because make_stream_auto_pipeline runs as plain factory
    Python, the AUTO_PIPELINE object is constructed eagerly here and captured
    by closure, which is what makes its .latency readable for sizing.

    latency= / start_latency= / max_latency= (keyword-only, default None)
    constrain that internal core AUTO_PIPELINE exactly as
    AUTO_PIPELINE(func, latency=, start_latency=, max_latency=) does -- core
    registers only, excluding the two boundary registers. The returned
    stream function deliberately has no .latency of its own: valid/ready
    handshaking is not a fixed latency. start_latency=S is a sweep hint: in a
    synthesizing build the bootstrap elaboration sizes the FIFO from S, the
    sweep's first iteration builds S core registers and grows from there if
    timing fails (the post-met trim may still go below S), and a correct guess
    skips the pin-and-confirm re-elaboration. Native sim and --comb /
    --no_synth / --yosys_json builds ignore start_latency / max_latency (core
    latency 0, as unconstrained); latency=N fixes the core at N everywhere.

    `func` must already be @hw_func-decorated, with a single annotated parameter and an
    annotated return type, e.g.:
        @hw_func
        def fft_2pt_w_omega_lut(i: fft_2pt_w_omega_lut_in_t) -> fft_2pt_out_t: ...

    Ports are declared as the two halves of a stream `@interface`, so this
    composes inside an interface function with no adapter:
        stream_auto_pipeline_func(stream_in_if: in_intrf.fwd_t, stream_out_if: out_intrf.fb_t) -> stream_auto_pipeline_t
        stream_auto_pipeline_t fields: .stream_out_if (out_intrf.fwd_t), .stream_in_if (in_intrf.fb_t)
    i.e. input port `stream_in_if` takes its feedforward half as an arg and returns
    its reverse half; output port `stream_out_if` does the reverse.

    Sizing metadata on the returned stream function, for callers that buffer
    around it (both regenerated by each re-elaboration):
        .auto_pipeline  the core AUTO_PIPELINE tag; .auto_pipeline.latency is
                        the core depth L, excluding the two boundary registers
        .max_in_flight  the int credit limit L+5 the in-flight counter and
                        ready logic enforce
    """
    if not is_hw_func(func):
        raise TypeError(
            f"make_stream_auto_pipeline(func): {func.__qualname__!r} must be "
            f"@hw_func-decorated before being passed in"
        )
    (in_type,) = hw_arg_types(func)
    out_type = hw_return_type(func)

    in_intrf = make_stream_interface(in_type)
    out_intrf = make_stream_interface(out_type)

    # Plain valid-only twins for func_stream/auto_pipelined_func below -- they
    # are purely combinational data-threading (no ready anywhere), not stream
    # ports, so they use genuinely one-directional types rather than a lone
    # half of the with-ready in_intrf.fwd_t/out_intrf.fwd_t (those are reserved
    # for stream_auto_pipeline's own real ports further down).
    in_plain_t = make_stream_t(in_type)
    out_plain_t = make_stream_t(out_type)

    # Thread .valid alongside .data so the AUTO_PIPELINE retiming balances
    # valid through the same number of stages it picks for func's data path.
    @hw_func
    def func_stream(x: in_plain_t) -> out_plain_t:
        rv: out_plain_t
        rv.data = func(x.data)
        rv.valid = x.valid
        return rv

    auto_pipelined_func, auto_pipeline_call = _auto_pipeline_with_io_regs(
        func_stream,
        has_input_reg=True,
        has_output_reg=True,
        latency=latency,
        start_latency=start_latency,
        max_latency=max_latency,
    )

    # A word's credit is out for L+5 cycles: input reg, L core regs, output
    # reg, the FIFO's 2-cycle push-to-valid, and the registered ready. That
    # many credits sustain 1 word/cycle. If the consumer stalls, all of them
    # end up in the FIFO: L+4 words of memory (make_fifo rounds up to a power
    # of two) plus the FIFO's output register.
    max_in_flight = auto_pipeline_call.latency + 5
    fifo_depth = max_in_flight - 1

    fifo_func, fifo_t = make_fifo(out_type, fifo_depth)

    counter_t = make_uint_t(max_in_flight.bit_length())

    @struct
    class stream_auto_pipeline_t(NamedTuple):
        stream_in_if: in_intrf.fb_t  # input port's reverse half travels out
        stream_out_if: out_intrf.fwd_t  # output port's feedforward half travels out

    @hw_func
    def stream_auto_pipeline(
        stream_in_if: in_intrf.fwd_t, stream_out_if: out_intrf.fb_t
    ) -> stream_auto_pipeline_t:
        o: stream_auto_pipeline_t

        # Count of words accepted into the pipeline but not yet read out of the FIFO.
        in_flight: Reg[counter_t]
        # Registered ready (matches the macro's static in_ready_reg): read old value,
        # written for next cycle further down.
        ready_reg: Reg[uint1_t]
        o.stream_in_if.ready = ready_reg

        # Free-flowing pipeline input, gated by ready.
        no_handshake_in: in_plain_t
        no_handshake_in.valid = stream_in_if.stream.valid & o.stream_in_if.ready
        no_handshake_in.data = stream_in_if.stream.data
        no_handshake_out: out_plain_t = auto_pipelined_func(no_handshake_in)

        # Free-flowing pipeline output into the FIFO; FIFO never overflows because
        # ready already accounted for in_flight < max_in_flight.
        f = fifo_func(
            stream_out_if.ready, no_handshake_out.data, no_handshake_out.valid
        )
        o.stream_out_if.stream = out_plain_t(data=f.data_out, valid=f.data_out_valid)

        # Update in-flight count / next-cycle ready from accept/retire this cycle.
        accepted: uint1_t = stream_in_if.stream.valid & o.stream_in_if.ready
        retired: uint1_t = o.stream_out_if.stream.valid & stream_out_if.ready

        ready_reg = in_flight < max_in_flight
        if accepted & ~retired:
            ready_reg = in_flight < (max_in_flight - 1)
            in_flight += 1
        elif retired & ~accepted:
            ready_reg = 1
            in_flight -= 1

        return o

    # The port interfaces (and their two halves), so callers can declare
    # matching ports / write interface functions over this module.
    stream_auto_pipeline.in_intrf = in_intrf
    stream_auto_pipeline.out_intrf = out_intrf
    stream_auto_pipeline.in_fwd_t = in_intrf.fwd_t
    stream_auto_pipeline.in_fb_t = in_intrf.fb_t
    stream_auto_pipeline.out_fwd_t = out_intrf.fwd_t
    stream_auto_pipeline.out_fb_t = out_intrf.fb_t
    # Sizing metadata (see docstring)
    stream_auto_pipeline.auto_pipeline = auto_pipeline_call
    stream_auto_pipeline.max_in_flight = max_in_flight
    return stream_auto_pipeline, stream_auto_pipeline_t
