// Verilator C++ driver for counter.py, printing its counter_debug output port:
//   pypelinec examples/pypeline/counter.py --sim --comb --verilator --main_cpp examples/pypeline/counter_verilator_main.cpp

// Names generated by the pypelinec tool (ex. clk is #defined to the clock port name)
#include "pipelinec_verilator.h"

// Generated by Verilator
#include "verilated.h"
#include "Vtop.h"

#include <iostream>
using namespace std;

int main(int argc, char *argv[]) {
    Vtop* g_top = new Vtop;
    for (uint64_t cycle = 0; cycle < 4; ++cycle) {
        g_top->clk = 0;
        g_top->eval();
        // Top level ports are members of Vtop
        cout << "cycle " << cycle << ": counter_debug: " << g_top->counter_debug << endl;
        g_top->clk = 1;
        g_top->eval();
    }
    delete g_top;
    return 0;
}
