#!/bin/bash
rm -rf *.log
rm -rf *.jou
rm -rf *.link_summary
rm -rf project_1
rm -rf .Xil
rm -rf .ipcache
rm -rf _x
rm -rf o
rm -rf xo
rm -rf main
rm -rf ip_repo
rm -rf kernel.ltx
rm -rf kernel.xclbin
rm -rf kernel.xclbin.info
rm -rf xsa.xml
rm -rf emconfig.json
rm -rf ext_metadata.json
rm -rf .run