#include "wire.h"
#include "uintN_t.h"

// Include I2S from PMOD
#include "i2s_pmod.c"

// Do basic I2S loopback
// Do I2S->AXIS loopback
// Do basic I2S->AXIS-> higher clock for fancier DSP

/*
https://reference.digilentinc.com/pmod/pmodi2s2/reference-manual
  Quick Start
  To set up a simple 44.1 kHz audio passthrough, three control signals need to be generated by the host system board.
  1. A master clock (MCLK) at a frequency of approximately 22.579 MHz.
  2. A serial clock (SCLK), which fully toggles once per 8 MCLK periods.
  3. A Left/Right Word Select signal, which fully toggles once per 64 SCLK periods.
  The Pmod I2S2's Master/Slave select jumper (JP1) should be placed into the Slave (SLV) position.
  Each of these control signals should be provided to the appropriate pin on both the top and bottom rows of the Pmod I2S2.
  The ADOUT_SDIN pin should be driven by the ADIN_SDOUT signal.
*/

#pragma MAIN_MHZ app 22.579
void app()
{
  // Read the incoming I2S signals
  i2s_to_app_t from_i2s = read_i2s_pmod();
  
  // Drive I2S clocking derived from current MCLK domain
  
  // Drive the outgoing I2S signals
  app_to_i2s_t to_i2s;
  write_i2s_pmod(to_i2s);
}
