
#include "global_fifo.h"

// Trying to replace autogenerated header syntax like
//  #include "clock_crossing/fast_to_slow.h" // Auto generated

#define ASYNC_CLK_CROSSING_WIDTH_DEPTH(data_t, name, WIDTH_STR, DEPTH) \
GLOBAL_FIFO_WIDTH_DEPTH(data_t, name, WIDTH_STR, DEPTH)

#define ASYNC_CLK_CROSSING(data_t, name, DEPTH) \
GLOBAL_FIFO(data_t, name, DEPTH)
