
#include "compiler.h"

// Trying to replace autogenerated header syntax like
//  #include "clock_crossing/fast_to_slow.h" // Auto generated

#define ASYNC_CLK_CROSSING_WIDTH_DEPTH(data_t, name, WIDTH_STR, DEPTH) \
data_t name[DEPTH]; \
typedef struct name##_write_t \
{ \
  uint1_t ready; \
}name##_write_t; \
typedef struct name##_read_t \
{ \
data_t data[WIDTH_STR]; \
uint1_t valid; \
}name##_read_t; \
name##_write_t PPCAT(name##_WRITE_, WIDTH_STR)(data_t write_data[WIDTH_STR], uint1_t write_enable) \
{ \
  name##_write_t unused; \
  return unused; \
} \
name##_read_t PPCAT(name##_READ_, WIDTH_STR)(uint1_t read_enable) \
{ \
  name##_read_t unused; \
  return unused; \
}

#define ASYNC_CLK_CROSSING(data_t, name, DEPTH) \
ASYNC_CLK_CROSSING_WIDTH_DEPTH(data_t, name, 1, DEPTH)
