#include "compiler.h"
#include "uintN_t.h"

#include "shared_resource_bus.h"

// Using this file as a hacky macro for looping to declare variable number of async fifos

/*
#define SHARED_RESOURCE_BUS_NAME
#define SHARED_RESOURCE_BUS_TYPE_NAME          
#define SHARED_RESOURCE_BUS_WR_REQ_TYPE      
#define SHARED_RESOURCE_BUS_WR_DATA_TYPE
#define SHARED_RESOURCE_BUS_WR_RESP_TYPE
#define SHARED_RESOURCE_BUS_RD_REQ_TYPE
#define SHARED_RESOURCE_BUS_RD_DATA_TYPE    
#define SHARED_RESOURCE_BUS_HOST_PORTS
#define SHARED_RESOURCE_BUS_HOST_CLK_MHZ
#define SHARED_RESOURCE_BUS_DEV_PORTS
#define SHARED_RESOURCE_BUS_DEV_CLK_MHZ
*/

SHARED_BUS_DECL(
  SHARED_RESOURCE_BUS_TYPE_NAME,
  SHARED_RESOURCE_BUS_WR_REQ_TYPE, SHARED_RESOURCE_BUS_WR_DATA_TYPE, SHARED_RESOURCE_BUS_WR_RESP_TYPE,
  SHARED_RESOURCE_BUS_RD_REQ_TYPE,
  SHARED_RESOURCE_BUS_RD_DATA_TYPE,
  SHARED_RESOURCE_BUS_NAME,
  SHARED_RESOURCE_BUS_HOST_PORTS,
  SHARED_RESOURCE_BUS_DEV_PORTS
)
#if SHARED_RESOURCE_BUS_HOST_PORTS > 0
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 1
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 2
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 3
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 4
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 5
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 6
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 7
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 8
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 9
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 10
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 11
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 12
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 13
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 14
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 15
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 16
#error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
#endif

// Wire ASYNC FIFOs to dev-host wires
MAIN_MHZ(PPCAT(SHARED_RESOURCE_BUS_NAME,_host_side_fifo_wiring), SHARED_RESOURCE_BUS_HOST_CLK_MHZ)
void PPCAT(SHARED_RESOURCE_BUS_NAME,_host_side_fifo_wiring)()
{
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 0
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 1
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 2
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 3
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 4
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 5
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 6
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 7
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 8
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 9
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 10
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 11
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 12
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 13
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 14
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 15
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 16
  #error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
  #endif
}
MAIN_MHZ(PPCAT(SHARED_RESOURCE_BUS_NAME,_dev_side_fifo_wiring), SHARED_RESOURCE_BUS_DEV_CLK_MHZ)
void PPCAT(SHARED_RESOURCE_BUS_NAME,_dev_side_fifo_wiring)()
{
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 0
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 1
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 2
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 3
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 4
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 5
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 6
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 7
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 8
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 9
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 10
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 11
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 12
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 13
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 14
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 15
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 16
  #error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
  #endif
}

#undef SHARED_RESOURCE_BUS_NAME
#undef SHARED_RESOURCE_BUS_TYPE_NAME          
#undef SHARED_RESOURCE_BUS_WR_REQ_TYPE      
#undef SHARED_RESOURCE_BUS_WR_DATA_TYPE
#undef SHARED_RESOURCE_BUS_WR_RESP_TYPE
#undef SHARED_RESOURCE_BUS_RD_REQ_TYPE
#undef SHARED_RESOURCE_BUS_RD_DATA_TYPE    
#undef SHARED_RESOURCE_BUS_HOST_PORTS
#undef SHARED_RESOURCE_BUS_HOST_CLK_MHZ
#undef SHARED_RESOURCE_BUS_DEV_PORTS
#undef SHARED_RESOURCE_BUS_DEV_CLK_MHZ