// Generated by Verilator
#include "verilated.h"
#include "Vtop.h" 

// TODO: How to compile these without fixed paths? Tried -I{dir}?
// Names and helper macro generated by PipelineC tool
#include "pipelinec_verilator.h"

// Module under test
#include "u24mult.h"

#include <iostream>
using namespace std;

int main(int argc, char *argv[]) {
    Vtop* g_top = new Vtop;
    
    // Run the simulation for 10 cycles
    uint64_t cycle = 0;
    while (cycle < 10)
    {
        // Set inputs
        uint24_t x = cycle;
        uint24_t y = cycle+1;
        g_top->x = x;
        g_top->y = y;
        
        // Print the PipelineC input vars
        cout << "cycle " << cycle << ": ";
        cout << "x " << g_top->x << " ";
        cout << "y " << g_top->y << " ";

        // Clock rising edge
        g_top->clk = 0;
        g_top->eval();
        g_top->clk = 1;
        g_top->eval();
        
        // Print the PipelineC output vars
        uint48_t sim_result = g_top->result;
        uint48_t c_result = u24mult(x, y);
        cout << "sim_result " << sim_result << " c_result " << c_result << " MATCH?: " << (sim_result==c_result) << endl;
        
        ++cycle;
    }

    return 0;
}
