// Names and helper macro generated by PipelineC tool
#include "/home/julian/pipelinec_output/verilator/pipelinec_verilator.h"

// Generated by Verilator
#include "verilated.h"
#include "Vtop.h" 

#include <iostream>
using namespace std;

int main(int argc, char *argv[]) {
    Vtop* g_top = new Vtop;
    
    // Run the simulation for 10 cycles
    uint64_t cycle = 0;
    while (cycle < 10)
    {
        // Set inputs
        g_top->x = cycle;
        g_top->y = cycle+1;
        
        // Print the PipelineC input vars
        cout << "cycle " << cycle << ": ";
        cout << "x " << g_top->x << " ";
        cout << "y " << g_top->y << " ";

        // Clock rising edge
        g_top->clk = 0;
        g_top->eval();
        g_top->clk = 1;
        g_top->eval();
        
        // Print the PipelineC output vars
        cout << "result " << g_top->result << endl;
        
        ++cycle;
    }

    return 0;
}
