#!/usr/bin/env python3
"""A real pypelinec build must drop a usable host module in its output dir.

`inst/host_types_test.py` proves the GENERATOR is right. This proves the
BUILD wires it up: run pypelinec on a design that streams a struct, then take
the file it wrote out of the output directory and use it the way a host would
-- from a process that cannot import anything from this repo -- and check its
bytes against pypeline's own type_to_bytes for the same design type.

That last comparison is the point. Everything else here (the file exists, it
imports) would still pass if the build handed the host a well-formed module
describing the wrong layout, which is exactly the failure this feature exists
to remove.
"""

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
COMPILER = HERE.parents[2] / "pypelinec"
REPO_ROOT = HERE.parents[3]
DESIGN = HERE / "type_axis_synth_test.py"

# Frames chosen so nothing is a fixed point by accident: an all-ones frame
# drives every leaf's mask (record_t's `state` is a 2-bit enum in a 1-byte
# leaf, so 0xFF there must come back masked), and the rest are arbitrary.
RAW_FRAMES = (
    b"\x00" * 13,
    b"\xff" * 13,
    bytes(range(13)),
    bytes(
        (0xA5, 0x01, 0x02, 0xDE, 0xAD, 0xBE, 0xEF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66)
    ),
)

_DRIVER = r"""
import json, os, sys

repo = os.path.abspath(sys.argv[3])
sys.path = [p for p in sys.path if not os.path.abspath(p or ".").startswith(repo)]
try:
    import pypeline  # noqa: F401
    raise SystemExit("pypeline importable; this would not test a real host")
except ImportError:
    pass

import pypeline_host_types as H


def plain(v):
    if hasattr(v, "_asdict"):
        return {k: plain(x) for k, x in v._asdict().items()}
    if isinstance(v, (list, tuple)):
        return [plain(x) for x in v]
    return int(v)


out = {"types": sorted(H.TYPES), "byte_length": H.record_t.BYTE_LENGTH, "frames": []}
for hexed in json.load(open(sys.argv[1])):
    value = H.record_t.from_bytes(bytes.fromhex(hexed))
    out["frames"].append(
        {"plain": plain(value), "reencoded": H.record_t.to_bytes(value).hex()}
    )
json.dump(out, open(sys.argv[2], "w"))
"""


def _expected():
    """What pypeline itself says those frames mean."""
    sys.path.insert(0, str(REPO_ROOT / "src"))
    sys.path.insert(0, str(REPO_ROOT / "include" / "pypeline"))
    sys.path.insert(0, str(HERE))
    import type_axis_synth_test as design
    from pypeline import type_from_bytes, type_to_bytes

    def plain(v):
        if hasattr(v, "_asdict"):
            return {k: plain(x) for k, x in v._asdict().items()}
        if isinstance(v, (list, tuple)):
            return [plain(x) for x in v]
        return int(v)

    out = []
    for raw in RAW_FRAMES:
        value = type_from_bytes(design.record_t, raw)
        out.append(
            {
                "plain": plain(value),
                "reencoded": type_to_bytes(design.record_t, value).hex(),
            }
        )
    return out


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out_dir")
    args = parser.parse_args()
    root = Path(args.out_dir or tempfile.mkdtemp(prefix="host_types_build_"))

    subprocess.run(
        [
            sys.executable,
            str(COMPILER),
            str(DESIGN),
            "--comb",
            "--no_synth",
            "--out_dir",
            str(root),
        ],
        check=True,
    )

    module = root / "host" / "pypeline_host_types.py"
    assert module.is_file(), f"build wrote no host module at {module}"
    text = module.read_text()
    assert "GENERATED by pypelinec" in text and "do not edit" in text
    assert "type_axis_synth_test.py" in text, "generated file does not name its design"

    work = Path(tempfile.mkdtemp(prefix="host_types_build_use_"))
    (work / "pypeline_host_types.py").write_text(text)
    (work / "drive.py").write_text(_DRIVER)
    frames_path, out_path = work / "frames.json", work / "out.json"
    frames_path.write_text(json.dumps([f.hex() for f in RAW_FRAMES]))
    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    subprocess.run(
        [
            sys.executable,
            str(work / "drive.py"),
            str(frames_path),
            str(out_path),
            str(REPO_ROOT),
        ],
        cwd=str(work),
        env=env,
        check=True,
    )
    got = json.loads(out_path.read_text())

    assert got["types"] == ["link_state_t", "record_t"], got["types"]
    assert got["byte_length"] == 13, got["byte_length"]
    expected = _expected()
    for raw, exp, res in zip(RAW_FRAMES, expected, got["frames"]):
        assert res["plain"] == exp["plain"], (raw.hex(), res["plain"], exp["plain"])
        assert res["reencoded"] == exp["reencoded"], (raw.hex(), res, exp)
    print(f"host_types_build_test PASS ({len(RAW_FRAMES)} frames via {module})")


if __name__ == "__main__":
    main()
