// Test bench
#include "arrays.h"
#include "intN_t.h"
#include "uintN_t.h"
#pragma PART "xc7a100tcsg324-1"

// Functions to test
#include "../fm_radio.h"

// Script not setup to generate other than i16
#define in_data_t int16_t
#define out_data_format "%d"

// IQ samples generated by python script
#include "samples.h"

// Configure IO for the unit under test
#define in_stream_t fir_decim_in_data_stream_type(decim_5x)
#define out_stream_t fir_decim_out_data_stream_type(decim_5x)
#define DO_IQ_IN_IQ_OUT \
i_output = decim_5x(i_input); \
q_output = decim_5x(q_input);

// The test bench sending samples into a module and printing output sampples
#pragma MAIN tb
void tb()
{
  static uint32_t cycle_counter;
  static in_data_t i_samples[I_SAMPLES_SIZE] = I_SAMPLES;
  static in_data_t q_samples[Q_SAMPLES_SIZE] = Q_SAMPLES;

  // Prepare input sample into DUT
  in_stream_t i_input;
  i_input.data = i_samples[0];
  i_input.valid = 1;
  in_stream_t q_input;
  q_input.data = q_samples[0];
  q_input.valid = 1;

  // Do one clock cycle, input valid and get output
  out_stream_t i_output;
  out_stream_t q_output;
  DO_IQ_IN_IQ_OUT

  // Print valid output samples
  if(i_output.valid&q_output.valid){
    printf("Cycle %d,Sample IQ =,"out_data_format","out_data_format"\n", cycle_counter, i_output.data, q_output.data);
  }

  // Prepare for next sample
  ARRAY_SHIFT_DOWN(i_samples, I_SAMPLES_SIZE, 1)
  ARRAY_SHIFT_DOWN(q_samples, Q_SAMPLES_SIZE, 1)
  cycle_counter+=1;
}