#include "compiler.h"
#include "uintN_t.h"

#include "shared_resource_bus.h"

// Using this file as a hacky macro for looping to declare variable number of async fifos

/*
#define SHARED_RESOURCE_BUS_NAME
#define SHARED_RESOURCE_BUS_TYPE_NAME          
#define SHARED_RESOURCE_BUS_WR_REQ_TYPE      
#define SHARED_RESOURCE_BUS_WR_DATA_TYPE
#define SHARED_RESOURCE_BUS_WR_RESP_TYPE
#define SHARED_RESOURCE_BUS_RD_REQ_TYPE
#define SHARED_RESOURCE_BUS_RD_DATA_TYPE    
#define SHARED_RESOURCE_BUS_HOST_PORTS
#define SHARED_RESOURCE_BUS_HOST_CLK_MHZ
#define SHARED_RESOURCE_BUS_DEV_PORTS
#define SHARED_RESOURCE_BUS_DEV_CLK_MHZ
*/

SHARED_BUS_DECL(
  SHARED_RESOURCE_BUS_TYPE_NAME,
  SHARED_RESOURCE_BUS_WR_REQ_TYPE, SHARED_RESOURCE_BUS_WR_DATA_TYPE, SHARED_RESOURCE_BUS_WR_RESP_TYPE,
  SHARED_RESOURCE_BUS_RD_REQ_TYPE,
  SHARED_RESOURCE_BUS_RD_DATA_TYPE,
  SHARED_RESOURCE_BUS_NAME,
  SHARED_RESOURCE_BUS_HOST_PORTS,
  SHARED_RESOURCE_BUS_DEV_PORTS
)
#if SHARED_RESOURCE_BUS_HOST_PORTS > 0
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 1
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 2
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 3
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 4
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 5
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 6
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 7
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 8
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 9
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 10
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 11
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 12
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 13
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 14
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 15
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 16
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 16)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 17
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 17)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 18
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 18)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 19
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 19)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 20
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 20)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 21
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 21)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 22
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 22)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 23
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 23)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 24
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 24)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 25
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 25)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 26
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 26)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 27
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 27)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 28
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 28)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 29
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 29)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 30
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 30)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 31
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 31)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 32
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 32)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 33
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 33)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 34
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 34)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 35
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 35)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 36
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 36)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 37
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 37)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 38
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 38)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 39
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 39)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 40
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 40)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 41
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 41)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 42
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 42)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 43
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 43)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 44
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 44)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 45
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 45)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 46
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 46)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 47
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 47)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 48
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 48)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 49
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 49)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 50
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 50)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 51
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 51)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 52
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 52)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 53
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 53)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 54
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 54)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 55
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 55)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 56
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 56)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 57
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 57)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 58
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 58)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 59
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 59)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 60
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 60)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 61
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 61)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 62
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 62)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 63
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 63)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 64
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 64)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 65
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 65)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 66
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 66)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 67
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 67)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 68
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 68)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 69
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 69)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 70
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 70)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 71
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 71)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 72
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 72)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 73
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 73)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 74
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 74)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 75
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 75)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 76
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 76)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 77
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 77)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 78
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 78)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 79
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 79)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 80
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 80)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 81
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 81)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 82
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 82)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 83
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 83)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 84
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 84)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 85
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 85)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 86
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 86)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 87
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 87)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 88
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 88)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 89
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 89)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 90
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 90)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 91
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 91)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 92
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 92)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 93
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 93)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 94
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 94)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 95
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 95)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 96
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 96)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 97
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 97)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 98
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 98)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 99
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 99)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 100
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 100)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 101
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 101)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 102
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 102)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 103
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 103)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 104
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 104)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 105
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 105)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 106
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 106)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 107
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 107)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 108
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 108)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 109
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 109)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 110
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 110)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 111
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 111)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 112
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 112)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 113
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 113)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 114
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 114)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 115
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 115)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 116
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 116)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 117
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 117)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 118
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 118)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 119
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 119)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 120
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 120)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 121
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 121)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 122
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 122)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 123
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 123)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 124
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 124)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 125
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 125)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 126
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 126)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 127
SHARED_BUS_ASYNC_FIFO_DECL(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 127)
#endif
#if SHARED_RESOURCE_BUS_HOST_PORTS > 128
#error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
#endif

// Wire ASYNC FIFOs to dev-host wires
MAIN_MHZ(PPCAT(SHARED_RESOURCE_BUS_NAME,_host_side_fifo_wiring), SHARED_RESOURCE_BUS_HOST_CLK_MHZ)
PRAGMA_MESSAGE(FUNC_WIRES PPCAT(SHARED_RESOURCE_BUS_NAME,_host_side_fifo_wiring))
void PPCAT(SHARED_RESOURCE_BUS_NAME,_host_side_fifo_wiring)()
{
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 0
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 1
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 2
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 3
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 4
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 5
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 6
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 7
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 8
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 9
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 10
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 11
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 12
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 13
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 14
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 15
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 16
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 16)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 17
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 17)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 18
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 18)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 19
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 19)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 20
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 20)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 21
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 21)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 22
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 22)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 23
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 23)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 24
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 24)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 25
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 25)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 26
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 26)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 27
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 27)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 28
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 28)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 29
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 29)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 30
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 30)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 31
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 31)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 32
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 32)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 33
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 33)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 34
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 34)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 35
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 35)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 36
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 36)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 37
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 37)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 38
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 38)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 39
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 39)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 40
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 40)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 41
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 41)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 42
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 42)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 43
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 43)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 44
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 44)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 45
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 45)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 46
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 46)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 47
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 47)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 48
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 48)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 49
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 49)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 50
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 50)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 51
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 51)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 52
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 52)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 53
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 53)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 54
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 54)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 55
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 55)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 56
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 56)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 57
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 57)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 58
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 58)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 59
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 59)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 60
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 60)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 61
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 61)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 62
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 62)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 63
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 63)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 64
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 64)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 65
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 65)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 66
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 66)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 67
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 67)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 68
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 68)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 69
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 69)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 70
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 70)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 71
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 71)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 72
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 72)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 73
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 73)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 74
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 74)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 75
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 75)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 76
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 76)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 77
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 77)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 78
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 78)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 79
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 79)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 80
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 80)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 81
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 81)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 82
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 82)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 83
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 83)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 84
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 84)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 85
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 85)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 86
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 86)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 87
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 87)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 88
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 88)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 89
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 89)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 90
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 90)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 91
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 91)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 92
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 92)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 93
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 93)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 94
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 94)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 95
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 95)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 96
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 96)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 97
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 97)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 98
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 98)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 99
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 99)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 100
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 100)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 101
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 101)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 102
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 102)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 103
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 103)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 104
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 104)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 105
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 105)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 106
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 106)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 107
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 107)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 108
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 108)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 109
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 109)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 110
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 110)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 111
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 111)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 112
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 112)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 113
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 113)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 114
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 114)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 115
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 115)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 116
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 116)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 117
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 117)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 118
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 118)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 119
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 119)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 120
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 120)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 121
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 121)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 122
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 122)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 123
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 123)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 124
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 124)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 125
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 125)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 126
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 126)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 127
  SHARED_BUS_ASYNC_FIFO_HOST_WIRING_PIPELINED(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 127)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 128
  #error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
  #endif
}
MAIN_MHZ(PPCAT(SHARED_RESOURCE_BUS_NAME,_dev_side_fifo_wiring), SHARED_RESOURCE_BUS_DEV_CLK_MHZ)
PRAGMA_MESSAGE(FUNC_WIRES PPCAT(SHARED_RESOURCE_BUS_NAME,_dev_side_fifo_wiring))
void PPCAT(SHARED_RESOURCE_BUS_NAME,_dev_side_fifo_wiring)()
{
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 0
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 0)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 1
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 1)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 2
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 2)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 3
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 3)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 4
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 4)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 5
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 5)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 6
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 6)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 7
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 7)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 8
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 8)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 9
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 9)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 10
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 10)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 11
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 11)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 12
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 12)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 13
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 13)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 14
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 14)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 15
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 15)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 16
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 16)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 17
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 17)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 18
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 18)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 19
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 19)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 20
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 20)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 21
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 21)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 22
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 22)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 23
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 23)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 24
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 24)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 25
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 25)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 26
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 26)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 27
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 27)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 28
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 28)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 29
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 29)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 30
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 30)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 31
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 31)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 32
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 32)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 33
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 33)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 34
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 34)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 35
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 35)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 36
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 36)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 37
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 37)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 38
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 38)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 39
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 39)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 40
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 40)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 41
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 41)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 42
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 42)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 43
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 43)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 44
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 44)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 45
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 45)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 46
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 46)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 47
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 47)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 48
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 48)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 49
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 49)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 50
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 50)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 51
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 51)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 52
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 52)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 53
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 53)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 54
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 54)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 55
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 55)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 56
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 56)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 57
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 57)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 58
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 58)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 59
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 59)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 60
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 60)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 61
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 61)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 62
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 62)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 63
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 63)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 64
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 64)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 65
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 65)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 66
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 66)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 67
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 67)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 68
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 68)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 69
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 69)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 70
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 70)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 71
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 71)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 72
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 72)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 73
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 73)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 74
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 74)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 75
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 75)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 76
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 76)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 77
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 77)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 78
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 78)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 79
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 79)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 80
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 80)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 81
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 81)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 82
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 82)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 83
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 83)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 84
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 84)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 85
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 85)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 86
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 86)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 87
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 87)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 88
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 88)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 89
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 89)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 90
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 90)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 91
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 91)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 92
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 92)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 93
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 93)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 94
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 94)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 95
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 95)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 96
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 96)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 97
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 97)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 98
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 98)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 99
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 99)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 100
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 100)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 101
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 101)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 102
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 102)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 103
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 103)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 104
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 104)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 105
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 105)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 106
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 106)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 107
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 107)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 108
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 108)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 109
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 109)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 110
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 110)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 111
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 111)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 112
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 112)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 113
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 113)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 114
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 114)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 115
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 115)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 116
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 116)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 117
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 117)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 118
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 118)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 119
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 119)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 120
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 120)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 121
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 121)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 122
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 122)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 123
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 123)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 124
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 124)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 125
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 125)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 126
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 126)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 127
  SHARED_BUS_ASYNC_FIFO_DEV_WIRING(SHARED_RESOURCE_BUS_TYPE_NAME, SHARED_RESOURCE_BUS_NAME, 127)
  #endif
  #if SHARED_RESOURCE_BUS_HOST_PORTS > 128
  #error "Increase shared_resource_bus_decl.h loop unrolling for more threads!"
  #endif
}

#undef SHARED_RESOURCE_BUS_NAME
#undef SHARED_RESOURCE_BUS_TYPE_NAME          
#undef SHARED_RESOURCE_BUS_WR_REQ_TYPE      
#undef SHARED_RESOURCE_BUS_WR_DATA_TYPE
#undef SHARED_RESOURCE_BUS_WR_RESP_TYPE
#undef SHARED_RESOURCE_BUS_RD_REQ_TYPE
#undef SHARED_RESOURCE_BUS_RD_DATA_TYPE    
#undef SHARED_RESOURCE_BUS_HOST_PORTS
#undef SHARED_RESOURCE_BUS_HOST_CLK_MHZ
#undef SHARED_RESOURCE_BUS_DEV_PORTS
#undef SHARED_RESOURCE_BUS_DEV_CLK_MHZ
