#!/usr/bin/env python3
"""Source of counter_waveform.svg: examples/pypeline/counter.py's cocotb+GHDL waveform,
drawn like a waveform viewer. Used by docs/README.md (Simulation).

Re-render from the repo root after changing counter.py:

    pypelinec examples/pypeline/counter.py --comb --sim --cocotb --ghdl --run 5 --out_dir counter_sim
    python3 docs/images/counter_waveform.py counter_sim/cocotb/top.vcd

which writes docs/images/counter_waveform.svg (the first 160 ns, four clock cycles).
"""

import os
import sys
from xml.sax.saxutils import escape


def parse_vcd(path):
    scopes = []
    id_to_names = {}
    timescale_fs = 1
    changes = {}  # id -> [(time_fs, value_str)]
    t = 0
    with open(path) as f:
        tokens_mode = None
        for line in f:
            s = line.strip()
            if not s:
                continue
            if s.startswith("$timescale"):
                tokens_mode = "timescale"
                continue
            if tokens_mode == "timescale":
                if s.startswith("$end"):
                    tokens_mode = None
                    continue
                num = "".join(c for c in s if c.isdigit())
                unit = s[len(num) :].strip()
                mult = {"fs": 1, "ps": 1000, "ns": 10**6, "us": 10**9}[unit]
                timescale_fs = int(num) * mult
                continue
            if s.startswith("$scope"):
                scopes.append(s.split()[2])
                continue
            if s.startswith("$upscope"):
                scopes.pop()
                continue
            if s.startswith("$var"):
                parts = s.split()
                vid = parts[3]
                name = parts[4]
                if len(parts) > 6 and parts[5].startswith("["):
                    name += parts[5]
                full = ".".join(scopes + [name])
                id_to_names.setdefault(vid, []).append(full)
                continue
            if s.startswith("$"):
                continue
            if s.startswith("#"):
                t = int(s[1:]) * timescale_fs
                continue
            if s[0] in "bB":
                val, vid = s[1:].split()
            else:
                val, vid = s[0], s[1:]
            changes.setdefault(vid, []).append((t, val))
    name_to_changes = {}
    for vid, names in id_to_names.items():
        for n in names:
            name_to_changes[n] = changes.get(vid, [])
    return name_to_changes, t


def to_hex(bits):
    if any(c not in "01" for c in bits):
        return "X"
    width = len(bits)
    return format(int(bits, 2), "0{}x".format((width + 3) // 4)).upper()


def main():
    vcd_path = sys.argv[1]
    out_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "counter_waveform.svg"
    )
    data, t_last = parse_vcd(vcd_path)
    t_end = 160 * 10**6  # four 40 ns clock cycles, in fs
    # The counter instance's name includes a hash of its source, so find it
    reg = [
        n
        for n in data
        if n.startswith("top.counter_0clk_") and n.endswith(".the_counter_reg[15:0]")
    ]
    assert len(reg) == 1, reg
    signals = [
        "top.clk_25p0",
        "top.counter_debug[15:0]",
        "top.counter_return_output[15:0]",
        reg[0],
    ]
    name_w = 410
    wave_w = 600
    row_h = 34
    top_h = 34
    width = name_w + wave_w
    height = top_h + row_h * len(signals) + 12
    ns = 10**6

    def x_of(t_fs):
        return name_w + 10 + (wave_w - 20) * t_fs / t_end

    out = []
    out.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="DejaVu Sans Mono, Menlo, Consolas, monospace">'
    )
    out.append(
        "  <!-- Generated by counter_waveform.py from counter.py's cocotb+GHDL top.vcd: re-render instead of editing. -->"
    )
    # Panes
    out.append(
        f'  <rect x="0" y="0" width="{name_w}" height="{height}" fill="#f2f2f2"/>'
    )
    out.append(
        f'  <rect x="{name_w}" y="0" width="{wave_w}" height="{height}" fill="#000000"/>'
    )
    out.append(
        f'  <line x1="{name_w}" y1="0" x2="{name_w}" y2="{height}" stroke="#808080"/>'
    )
    out.append(f'  <text x="10" y="22" font-size="13" fill="#202020">Signals</text>')
    out.append(
        f'  <line x1="0" y1="{top_h}" x2="{width}" y2="{top_h}" stroke="#808080"/>'
    )
    # Time axis: tick every 40 ns
    step = 40 * ns
    tk = 0
    while tk < t_end:
        x = x_of(tk)
        out.append(
            f'  <line x1="{x:.1f}" y1="{top_h - 8}" x2="{x:.1f}" y2="{top_h}" stroke="#c8c8c8"/>'
        )
        out.append(
            f'  <text x="{x + 3:.1f}" y="{top_h - 12}" font-size="11" fill="#c8c8c8">{tk // ns} ns</text>'
        )
        out.append(
            f'  <line x1="{x:.1f}" y1="{top_h}" x2="{x:.1f}" y2="{height}" stroke="#333333" stroke-dasharray="2,4"/>'
        )
        tk += step
    green = "#3ddc3d"
    for i, sig in enumerate(signals):
        y0 = top_h + i * row_h
        yt = y0 + 8
        yb = y0 + row_h - 8
        ym = (yt + yb) / 2
        label = sig
        out.append(
            f'  <text x="10" y="{ym + 4.5:.1f}" font-size="13" fill="#000000">{escape(label)}</text>'
        )
        ch = data[sig]
        if not ch:
            raise SystemExit(f"no changes for {sig}")
        # Drop duplicate consecutive values
        segs = []
        for t, v in ch:
            if t >= t_end:
                break
            if segs and segs[-1][1] == v:
                continue
            if segs and segs[-1][0] == t:
                segs[-1] = (t, v)
                continue
            segs.append((t, v))
        is_bit = all(len(v) == 1 for _, v in segs)
        if is_bit:
            pts = []
            for j, (t, v) in enumerate(segs):
                x = x_of(t)
                y = yt if v == "1" else yb
                if pts:
                    pts.append(f"{x:.1f},{pts[-1].split(',')[1]}")
                pts.append(f"{x:.1f},{y:.1f}")
            pts.append(f"{x_of(t_end):.1f},{pts[-1].split(',')[1]}")
            out.append(
                f'  <polyline points="{" ".join(pts)}" fill="none" stroke="{green}" stroke-width="1.5"/>'
            )
        else:
            for j, (t, v) in enumerate(segs):
                xa = x_of(t)
                xb = x_of(segs[j + 1][0]) if j + 1 < len(segs) else x_of(t_end)
                d = 4 if xb - xa > 10 else 0
                path = (
                    f"M{xa:.1f},{ym:.1f} L{xa + d:.1f},{yt:.1f} L{xb - d:.1f},{yt:.1f} "
                    f"L{xb:.1f},{ym:.1f} L{xb - d:.1f},{yb:.1f} L{xa + d:.1f},{yb:.1f} Z"
                )
                out.append(
                    f'  <path d="{path}" fill="none" stroke="{green}" stroke-width="1.5"/>'
                )
                text = to_hex(v)
                if xb - xa > 9 * len(text):
                    out.append(
                        f'  <text x="{xa + 7:.1f}" y="{ym + 4.5:.1f}" font-size="12" fill="#ffffff">{text}</text>'
                    )
    out.append("</svg>")
    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
