#include "compiler.h"

// TODO rename the DECL_OUTPUT's with some kind of #ifdef PMOD_O4_OUT etc

#ifdef PMOD_O4_WIRE
GLOBAL_OUT_WIRE_CONNECT(uint1_t, PMOD_O4_WIRE, PPCAT(PMOD_NAME,_o4))
#undef PMOD_O4_WIRE
#else
//DECL_OUTPUT(uint1_t, PPCAT(PMOD_NAME,_o4))
#endif

#ifdef PMOD_I4_WIRE
GLOBAL_IN_WIRE_CONNECT(uint1_t, PPCAT(PMOD_NAME,_i4), PMOD_I4_WIRE)
#undef PMOD_I4_WIRE
#else
//DECL_INPUT(uint1_t, PPCAT(PMOD_NAME,_i4))
#endif

#ifdef PMOD_O3_WIRE
GLOBAL_OUT_WIRE_CONNECT(uint1_t, PMOD_O3_WIRE, PPCAT(PMOD_NAME,_o3))
#undef PMOD_O3_WIRE
#else
//DECL_OUTPUT(uint1_t, PPCAT(PMOD_NAME,_o3))
#endif

#ifdef PMOD_I3_WIRE
GLOBAL_IN_WIRE_CONNECT(uint1_t, PPCAT(PMOD_NAME,_i3), PMOD_I3_WIRE)
#undef PMOD_I3_WIRE
#else
//DECL_INPUT(uint1_t, PPCAT(PMOD_NAME,_i3))
#endif

#ifdef PMOD_O2_WIRE
GLOBAL_OUT_WIRE_CONNECT(uint1_t, PMOD_O2_WIRE, PPCAT(PMOD_NAME,_o2))
#undef PMOD_O2_WIRE
#else
//DECL_OUTPUT(uint1_t, PPCAT(PMOD_NAME,_o2))
#endif

#ifdef PMOD_I2_WIRE
GLOBAL_IN_WIRE_CONNECT(uint1_t, PPCAT(PMOD_NAME,_i2), PMOD_I2_WIRE)
#undef PMOD_I2_WIRE
#else
//DECL_INPUT(uint1_t, PPCAT(PMOD_NAME,_i2))
#endif

#ifdef PMOD_O1_WIRE
GLOBAL_OUT_WIRE_CONNECT(uint1_t, PMOD_O1_WIRE, PPCAT(PMOD_NAME,_o1))
#undef PMOD_O1_WIRE
#else
//DECL_OUTPUT(uint1_t, PPCAT(PMOD_NAME,_o1))
#endif

#ifdef PMOD_I1_WIRE
GLOBAL_IN_WIRE_CONNECT(uint1_t, PPCAT(PMOD_NAME,_i1), PMOD_I1_WIRE)
#undef PMOD_I1_WIRE
#else
//DECL_INPUT(uint1_t, PPCAT(PMOD_NAME,_i1))
#endif

#undef PMOD_NAME



